CREATE TABLE IF NOT EXISTS raw.cow_trades (
	block_number integer,
	block_date date,
	block_time timestamp,
	tx_hash text,
	order_uid text PRIMARY KEY,
	trader text,
	sell_token_address text,
	sell_token text,
	buy_token_address text,
	buy_token text,
	token_pair text,
	order_type text,
	partial_fill bool,
	fill_proportion int8,
	surplus_usd numeric,
	units_sold numeric,
	atoms_sold text,
	units_bought numeric,
	atoms_bought text,
	usd_value numeric,
	buy_price numeric,
	buy_value_usd numeric,
	sell_price numeric,
	sell_value_usd numeric,
	fee int8,
	fee_atoms int8,
	fee_usd int8
);